-- TRAC JHS LAN-Based Student Admission and Records Management System
-- PostgreSQL schema for Supabase (converted from MySQL)
-- Import on Supabase, dedicated schema: trac_jhs_sarms
--
-- Usage:
--   PGOPTIONS='-c search_path=trac_jhs_sarms,public' \
--   psql "host=aws-0-<region>.pooler.supabase.com port=6543 dbname=postgres user=postgres.<ref> sslmode=require" \
--   -f database/schema.sql

CREATE SCHEMA IF NOT EXISTS trac_jhs_sarms;

-- Trigger function: set updated_at column to NOW() on row UPDATE
CREATE OR REPLACE FUNCTION trac_jhs_sarms.trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users  (Admin = registrar, Staff = encoder)
-- ---------------------------------------------------------------------------
CREATE TABLE trac_jhs_sarms.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    role VARCHAR(15) NOT NULL CHECK (role IN ('registrar', 'encoder')) DEFAULT 'encoder',
    is_active SMALLINT NOT NULL DEFAULT 1,
    last_active TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_username UNIQUE (username)
);
CREATE INDEX idx_users_role ON trac_jhs_sarms.users (role);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.users
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.school_years (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(20) NOT NULL,
    is_active SMALLINT NOT NULL DEFAULT 0,
    start_date DATE NULL,
    end_date DATE NULL,
    CONSTRAINT uq_school_years_label UNIQUE (label)
);

CREATE TABLE trac_jhs_sarms.grade_levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT uq_grade_levels_name UNIQUE (name)
);

CREATE TABLE trac_jhs_sarms.sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_level_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT fk_sections_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT uq_section_grade_name UNIQUE (grade_level_id, name)
);

-- ---------------------------------------------------------------------------
-- students  (personal profile)
-- ---------------------------------------------------------------------------
CREATE TABLE trac_jhs_sarms.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id_no VARCHAR(20) NOT NULL,
    lrn VARCHAR(12) NULL,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    suffix VARCHAR(10) NULL,
    birthdate DATE NOT NULL,
    sex VARCHAR(10) NOT NULL CHECK (sex IN ('Male', 'Female')),
    address TEXT NOT NULL,
    contact_number VARCHAR(20) NULL,
    guardian_name VARCHAR(150) NOT NULL,
    guardian_relationship VARCHAR(50) NOT NULL,
    guardian_contact VARCHAR(20) NOT NULL,
    previous_school VARCHAR(200) NULL,
    remarks TEXT NULL,
    status VARCHAR(15) NOT NULL CHECK (status IN ('active', 'transferred', 'graduated', 'dropped')) DEFAULT 'active',
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_students_created_by FOREIGN KEY (created_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uq_students_id_no UNIQUE (student_id_no),
    CONSTRAINT uq_students_lrn UNIQUE (lrn)
);
CREATE INDEX idx_students_name ON trac_jhs_sarms.students (last_name, first_name);
CREATE INDEX idx_students_status ON trac_jhs_sarms.students (status);

CREATE TRIGGER trg_students_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.students
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.admissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NULL,
    application_no VARCHAR(20) NOT NULL,
    school_year_id INTEGER NOT NULL,
    grade_level_id INTEGER NOT NULL,
    enrollment_type VARCHAR(15) NOT NULL CHECK (enrollment_type IN ('new', 'returning', 'transferee')) DEFAULT 'new',
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    suffix VARCHAR(10) NULL,
    lrn VARCHAR(12) NULL,
    birthdate DATE NOT NULL,
    sex VARCHAR(10) NOT NULL CHECK (sex IN ('Male', 'Female')),
    address TEXT NOT NULL,
    contact_number VARCHAR(20) NULL,
    guardian_name VARCHAR(150) NOT NULL,
    guardian_relationship VARCHAR(50) NOT NULL,
    guardian_contact VARCHAR(20) NOT NULL,
    previous_school VARCHAR(200) NULL,
    documents_submitted JSONB NULL,
    status VARCHAR(10) NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    reviewed_by INTEGER NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    review_notes TEXT NULL,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_admissions_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_admissions_school_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id),
    CONSTRAINT fk_admissions_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT fk_admissions_created_by FOREIGN KEY (created_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT fk_admissions_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uq_admissions_app_no UNIQUE (application_no)
);
CREATE INDEX idx_admissions_status ON trac_jhs_sarms.admissions (status);
CREATE INDEX idx_admissions_name ON trac_jhs_sarms.admissions (last_name, first_name);

CREATE TRIGGER trg_admissions_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.admissions
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    school_year_id INTEGER NOT NULL,
    grade_level_id INTEGER NOT NULL,
    section_id INTEGER NULL,
    enrollment_type VARCHAR(15) NOT NULL CHECK (enrollment_type IN ('new', 'returning', 'transferee')),
    status VARCHAR(15) NOT NULL CHECK (status IN ('enrolled', 'completed', 'withdrawn')) DEFAULT 'enrolled',
    enrolled_at DATE NOT NULL,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_enrollments_school_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id),
    CONSTRAINT fk_enrollments_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT fk_enrollments_section FOREIGN KEY (section_id) REFERENCES trac_jhs_sarms.sections(id),
    CONSTRAINT fk_enrollments_created_by FOREIGN KEY (created_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uniq_student_school_year UNIQUE (student_id, school_year_id)
);
CREATE INDEX idx_enrollments_status ON trac_jhs_sarms.enrollments (status);

-- Academic history linked to student + school year (records module)
CREATE TABLE trac_jhs_sarms.academic_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    school_year_id INTEGER NOT NULL,
    grade_level_id INTEGER NOT NULL,
    general_average NUMERIC(5,2) NULL,
    promotional_status VARCHAR(15) NULL CHECK (promotional_status IN ('Promoted', 'Retained', 'Incomplete')),
    attendance_days INTEGER NULL,
    awards TEXT NULL,
    record_notes TEXT NULL,
    archived SMALLINT NOT NULL DEFAULT 0,
    updated_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_records_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_records_school_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id),
    CONSTRAINT fk_records_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT fk_records_updated_by FOREIGN KEY (updated_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uniq_record_student_year UNIQUE (student_id, school_year_id)
);
CREATE INDEX idx_records_updated_by ON trac_jhs_sarms.academic_records (updated_by);

CREATE TRIGGER trg_academic_records_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.academic_records
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id INTEGER NULL,
    details TEXT NULL,
    ip_address VARCHAR(45) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES trac_jhs_sarms.users(id)
);
CREATE INDEX idx_audit_created ON trac_jhs_sarms.audit_logs (created_at);

CREATE TABLE trac_jhs_sarms.transfer_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
    counterpart_school VARCHAR(200) NOT NULL,
    request_date DATE NOT NULL,
    first_attendance_date DATE NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'documents_sent', 'documents_received', 'completed', 'escalated')) DEFAULT 'pending',
    notes TEXT NULL,
    escalated_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_transfer_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_transfer_created_by FOREIGN KEY (created_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT fk_transfer_updated_by FOREIGN KEY (updated_by) REFERENCES trac_jhs_sarms.users(id)
);
CREATE INDEX idx_transfer_status ON trac_jhs_sarms.transfer_requests (status);
CREATE INDEX idx_transfer_student ON trac_jhs_sarms.transfer_requests (student_id);

CREATE TRIGGER trg_transfer_requests_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.transfer_requests
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.sf10_grade_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    school_year_id INTEGER NOT NULL,
    grade_level_id INTEGER NOT NULL,
    learning_area VARCHAR(80) NOT NULL,
    q1_rating NUMERIC(5,2) NULL,
    q2_rating NUMERIC(5,2) NULL,
    q3_rating NUMERIC(5,2) NULL,
    q4_rating NUMERIC(5,2) NULL,
    final_rating NUMERIC(5,2) NULL,
    remarks VARCHAR(50) NULL,
    updated_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_sf10_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_sf10_school_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id),
    CONSTRAINT fk_sf10_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT fk_sf10_updated_by FOREIGN KEY (updated_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uniq_sf10_entry UNIQUE (student_id, school_year_id, grade_level_id, learning_area)
);
CREATE INDEX idx_sf10_updated_by ON trac_jhs_sarms.sf10_grade_entries (updated_by);

CREATE TRIGGER trg_sf10_grade_entries_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.sf10_grade_entries
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.app_settings (
    setting_key VARCHAR(50) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_app_settings_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.app_settings
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

CREATE TABLE trac_jhs_sarms.lis_import_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    school_year_id INTEGER NULL,
    rows_total INTEGER NOT NULL DEFAULT 0,
    rows_created INTEGER NOT NULL DEFAULT 0,
    rows_updated INTEGER NOT NULL DEFAULT 0,
    rows_skipped INTEGER NOT NULL DEFAULT 0,
    rows_errors INTEGER NOT NULL DEFAULT 0,
    error_details TEXT NULL,
    imported_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lis_import_user FOREIGN KEY (imported_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT fk_lis_import_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id)
);

-- ---------------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------------
INSERT INTO trac_jhs_sarms.grade_levels (name) VALUES
    ('Grade 7'), ('Grade 8'), ('Grade 9'), ('Grade 10');

INSERT INTO trac_jhs_sarms.sections (grade_level_id, name) VALUES
    (1, 'Makiling'), (1, 'Mayon'),
    (2, 'Makiling'), (2, 'Mayon'),
    (3, 'Makiling'), (3, 'Mayon'),
    (4, 'Makiling'), (4, 'Mayon');

INSERT INTO trac_jhs_sarms.school_years (label, is_active, start_date, end_date) VALUES
    ('2025-2026', 1, '2025-06-01', '2026-03-31');

-- Default credentials (change after first login):
-- registrar / Registrar@2026
-- encoder   / Encoder@2026
INSERT INTO trac_jhs_sarms.users (username, password_hash, full_name, role) VALUES
    ('registrar', '$2y$10$J3yYuFMGsf89Ae/Li/IMEeYsVEf85EHrIH0DzZUKrYhsl5.TbjFki', 'School Registrar', 'registrar'),
    ('encoder', '$2y$10$uqu6a1xzHGqOM/DktEsUr..9dZT1B/BkOdLqVJznwApTwubYEeKZu', 'Data Encoder', 'encoder');