<?php

declare(strict_types=1);

require_once __DIR__ . '/../../config/app.php';
require_once __DIR__ . '/../../includes/layout.php';

require_registrar();

$backupDir = __DIR__ . '/../../backups';
ensure_dir($backupDir);

$existingBackups = array_values(array_filter(
    scandir($backupDir) ?: [],
    static fn (string $file): bool => str_ends_with($file, '.sql')
));
rsort($existingBackups);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_csrf();
    $filename = 'trac_jhs_backup_' . date('Y-m-d_His') . '.sql';
    $filepath = $backupDir . '/' . $filename;

    $tables = [];
    $result = db()->query('SHOW TABLES');
    while ($row = $result->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    $dump = "-- TRAC JHS SARMS Database Backup\n";
    $dump .= '-- Generated: ' . date('Y-m-d H:i:s') . "\n";
    $dump .= '-- Generated by: ' . ($_SESSION['user']['full_name'] ?? 'Registrar') . "\n\n";
    $dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $table) {
        $createStmt = db()->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_NUM);
        $dump .= "DROP TABLE IF EXISTS `{$table}`;\n";
        $dump .= $createStmt[1] . ";\n\n";

        $rows = db()->query("SELECT * FROM `{$table}`")->fetchAll(PDO::FETCH_ASSOC);
        foreach ($rows as $row) {
            $columns = array_map(static fn ($col) => '`' . str_replace('`', '``', $col) . '`', array_keys($row));
            $values = array_map(static function ($value) {
                if ($value === null) {
                    return 'NULL';
                }

                return "'" . str_replace("'", "''", (string) $value) . "'";
            }, array_values($row));

            $dump .= 'INSERT INTO `' . $table . '` (' . implode(', ', $columns) . ') VALUES (' . implode(', ', $values) . ");\n";
        }
        $dump .= "\n";
    }

    $dump .= "SET FOREIGN_KEY_CHECKS=1;\n";

    file_put_contents($filepath, $dump);
    audit_log('backup', 'database', null, "Exported backup {$filename}");
    flash('success', "Database backup created: {$filename}");
    redirect('/modules/admin/backup.php');
}

render_header('Database Backup', 'backup');
?>
<div class="panel-card glass-panel mb-3">
    <h3>Registrar Backup Authority</h3>
    <p class="text-muted mb-0">
        The School Registrar may perform periodic manual backups by exporting the MySQL database.
        Store backup files on a separate storage device to protect against hardware failure.
    </p>
</div>

<div class="row g-3">
    <div class="col-lg-5">
        <div class="panel-card glass-panel">
            <h3>Create New Backup</h3>
            <p class="text-muted">Exports all tables and data into a downloadable SQL file.</p>
            <form method="post">
        <?= csrf_field() ?>
                <button type="submit" class="btn btn-primary"><i class="bi bi-download"></i> Export Database</button>
            </form>
        </div>
    </div>
    <div class="col-lg-7">
        <div class="table-card glass-panel">
            <h3>Available Backups</h3>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Filename</th>
                            <th>Size</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (!$existingBackups): ?>
                            <tr><td colspan="3" class="text-muted">No backups created yet.</td></tr>
                        <?php endif; ?>
                        <?php foreach ($existingBackups as $file): ?>
                            <?php $path = $backupDir . '/' . $file; ?>
                            <tr>
                                <td><?= e($file) ?></td>
                                <td><?= e(number_format(filesize($path) / 1024, 2)) ?> KB</td>
                                <td><a class="btn btn-sm btn-outline-light" href="<?= e(url('/modules/admin/download_backup.php?file=<?= e(rawurlencode($file)) ?>')) ?>">Download</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<?php
render_footer();
