<?php

declare(strict_types=1);

require_once __DIR__ . '/../../config/app.php';
require_once __DIR__ . '/../../includes/layout.php';

require_registrar();

$backupDir = __DIR__ . '/../../backups';
ensure_dir($backupDir);

$existingBackups = array_values(array_filter(
    scandir($backupDir) ?: [],
    static fn (string $file): bool => str_ends_with($file, '.sql')
));
rsort($existingBackups);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_csrf();
    $filename = 'trac_jhs_backup_' . date('Y-m-d_His') . '.sql';
    $filepath = $backupDir . '/' . $filename;

    // PostgreSQL-compatible logical dump: TRUNCATE + INSERTs per table.
    // No DDL (schema.sql is checked into the repo), so dumps are portable
    // across environments and re-imports are safe (TRUNCATE CASCADE handles
    // foreign-key ordering).
    $tables = db()->query(
        "SELECT tablename FROM pg_tables
          WHERE schemaname = current_schema()
          ORDER BY tablename"
    )->fetchAll(PDO::FETCH_COLUMN);

    $dump  = "-- TRAC JHS SARMS Database Backup (logical dump)\n";
    $dump .= '-- Generated: ' . date('Y-m-d H:i:s') . "\n";
    $dump .= '-- Generated by: ' . ($_SESSION['user']['full_name'] ?? 'Registrar') . "\n";
    $dump .= '-- Schema: ' . db()->query('SELECT current_schema()')->fetchColumn() . "\n";
    $dump .= "-- Target: PostgreSQL (logical dump — TRUNCATE + INSERTs)\n";
    $dump .= "-- Restore with: \\i {$filename}  (or run via modules/admin/restore.php)\n\n";
    $dump .= "BEGIN;\n\n";

    foreach ($tables as $table) {
        // Defensive: skip non-table objects (views, sequences) if any are picked up.
        $kind = db()->prepare(
            "SELECT c.relkind FROM pg_class c
              JOIN pg_namespace n ON n.oid = c.relnamespace
              WHERE n.nspname = current_schema() AND c.relname = :t"
        );
        $kind->execute(['t' => $table]);
        if ($kind->fetchColumn() !== 'r') {
            continue;
        }

        // Identify columns in declared order so INSERT column lists match.
        $columns = db()->prepare(
            "SELECT column_name FROM information_schema.columns
              WHERE table_schema = current_schema() AND table_name = :t
              ORDER BY ordinal_position"
        );
        $columns->execute(['t' => $table]);
        $colList = $columns->fetchAll(PDO::FETCH_COLUMN);

        if (!$colList) {
            continue;
        }

        $dump .= "-- Table: {$table}\n";
        $dump .= 'TRUNCATE TABLE "' . str_replace('"', '""', $table) . '" RESTART IDENTITY CASCADE;' . "\n";

        $colListQuoted = array_map(
            static fn (string $c): string => '"' . str_replace('"', '""', $c) . '"',
            $colList
        );

        $selectList = implode(', ', array_map(
            static fn (string $c): string =>
                'COALESCE('
                . '"' . str_replace('"', '""', $c) . '"'
                . '::text, \'\')',
            $colList
        ));

        $rows = db()->query(
            'SELECT ' . $selectList . ' FROM "' . str_replace('"', '""', $table) . '"'
        )->fetchAll(PDO::FETCH_NUM);

        if (!$rows) {
            $dump .= "-- (no rows)\n\n";
            continue;
        }

        $dump .= 'INSERT INTO "' . str_replace('"', '""', $table) . '" ('
               . implode(', ', $colListQuoted) . ') VALUES';

        $valueRows = [];
        foreach ($rows as $row) {
            $vals = array_map(
                static function ($v): string {
                    if ($v === null || $v === '') {
                        return 'NULL';
                    }
                    // Postgres E'...\'' string escape: backslash + single quote.
                    return "E'" . str_replace(
                        ['\\', "'"],
                        ['\\\\', "''"],
                        (string) $v
                    ) . "'";
                },
                $row
            );
            $valueRows[] = '(' . implode(', ', $vals) . ')';
        }
        $dump .= "\n  " . implode(",\n  ", $valueRows) . ";\n\n";
    }

    $dump .= "COMMIT;\n";

    file_put_contents($filepath, $dump);
    audit_log('backup', 'database', null, "Exported backup {$filename}");
    flash('success', "Database backup created: {$filename}");
    redirect('/modules/admin/backup.php');
}

render_header('Database Backup', 'backup');
?>
<div class="panel-card glass-panel mb-3">
    <h3>Registrar Backup Authority</h3>
    <p class="text-muted mb-0">
        The School Registrar may perform periodic manual backups by exporting the database.
        Backups are logical dumps (TRUNCATE + INSERT statements) — schema is excluded
        because it is version-controlled. Store backup files on a separate storage device
        to protect against hardware failure.
    </p>
</div>

<div class="row g-3">
    <div class="col-lg-5">
        <div class="panel-card glass-panel">
            <h3>Create New Backup</h3>
            <p class="text-muted">Exports all rows from all tables into a downloadable SQL file.</p>
            <form method="post">
        <?= csrf_field() ?>
                <button type="submit" class="btn btn-primary"><i class="bi bi-download"></i> Export Database</button>
            </form>
        </div>
    </div>
    <div class="col-lg-7">
        <div class="table-card glass-panel">
            <h3>Available Backups</h3>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Filename</th>
                            <th>Size</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (!$existingBackups): ?>
                            <tr><td colspan="3" class="text-muted">No backups created yet.</td></tr>
                        <?php endif; ?>
                        <?php foreach ($existingBackups as $file): ?>
                            <?php $path = $backupDir . '/' . $file; ?>
                            <tr>
                                <td><?= e($file) ?></td>
                                <td><?= e(number_format(filesize($path) / 1024, 2)) ?> KB</td>
                                <td><a class="btn btn-sm btn-outline-light" href="<?= e(url('/modules/admin/download_backup.php?file=' . rawurlencode($file))) ?>">Download</a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
        </div>
    </div>
</div>
<?php
render_footer();