-- Phase 2 migration: transfers, SF10 grade entries, user last_active
-- PostgreSQL syntax. Run AFTER schema.sql on existing installations.
-- Tables and column added here already exist in schema.sql on fresh
-- installs, so this migration is largely a no-op when applied to a
-- database that already matches schema.sql — IF NOT EXISTS guards
-- make it safe either way.

SET search_path = trac_jhs_sarms, public;

-- users.last_active (added in phase 2 to track per-user activity).
ALTER TABLE trac_jhs_sarms.users
    ADD COLUMN IF NOT EXISTS last_active TIMESTAMPTZ NULL DEFAULT NULL;

-- transfer_requests
CREATE TABLE IF NOT EXISTS trac_jhs_sarms.transfer_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
    counterpart_school VARCHAR(200) NOT NULL,
    request_date DATE NOT NULL,
    first_attendance_date DATE NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'documents_sent', 'documents_received', 'completed', 'escalated')) DEFAULT 'pending',
    notes TEXT NULL,
    escalated_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_transfer_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_transfer_created_by FOREIGN KEY (created_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT fk_transfer_updated_by FOREIGN KEY (updated_by) REFERENCES trac_jhs_sarms.users(id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_status ON trac_jhs_sarms.transfer_requests (status);
CREATE INDEX IF NOT EXISTS idx_transfer_student ON trac_jhs_sarms.transfer_requests (student_id);

-- Drop and recreate the updated_at trigger (idempotent via DROP IF EXISTS).
DROP TRIGGER IF EXISTS trg_transfer_requests_updated_at ON trac_jhs_sarms.transfer_requests;
CREATE TRIGGER trg_transfer_requests_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.transfer_requests
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();

-- sf10_grade_entries
CREATE TABLE IF NOT EXISTS trac_jhs_sarms.sf10_grade_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    school_year_id INTEGER NOT NULL,
    grade_level_id INTEGER NOT NULL,
    learning_area VARCHAR(80) NOT NULL,
    q1_rating NUMERIC(5,2) NULL,
    q2_rating NUMERIC(5,2) NULL,
    q3_rating NUMERIC(5,2) NULL,
    q4_rating NUMERIC(5,2) NULL,
    final_rating NUMERIC(5,2) NULL,
    remarks VARCHAR(50) NULL,
    updated_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sf10_student FOREIGN KEY (student_id) REFERENCES trac_jhs_sarms.students(id),
    CONSTRAINT fk_sf10_school_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id),
    CONSTRAINT fk_sf10_grade FOREIGN KEY (grade_level_id) REFERENCES trac_jhs_sarms.grade_levels(id),
    CONSTRAINT fk_sf10_updated_by FOREIGN KEY (updated_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT uniq_sf10_entry UNIQUE (student_id, school_year_id, grade_level_id, learning_area)
);

CREATE INDEX IF NOT EXISTS idx_sf10_updated_by ON trac_jhs_sarms.sf10_grade_entries (updated_by);

DROP TRIGGER IF EXISTS trg_sf10_grade_entries_updated_at ON trac_jhs_sarms.sf10_grade_entries;
CREATE TRIGGER trg_sf10_grade_entries_updated_at
    BEFORE UPDATE ON trac_jhs_sarms.sf10_grade_entries
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();