-- Phase 3: LIS CSV export/import support (PostgreSQL)
-- Run AFTER schema.sql on existing installations. Tables already exist in
-- schema.sql, so this migration is a no-op on fresh installs — IF NOT EXISTS
-- guards make it safe to apply either before or after schema.sql.
SET search_path = trac_jhs_sarms, public;

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(50) NOT NULL PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lis_import_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    school_year_id INTEGER NULL,
    rows_total INTEGER NOT NULL DEFAULT 0,
    rows_created INTEGER NOT NULL DEFAULT 0,
    rows_updated INTEGER NOT NULL DEFAULT 0,
    rows_skipped INTEGER NOT NULL DEFAULT 0,
    rows_errors INTEGER NOT NULL DEFAULT 0,
    error_details TEXT NULL,
    imported_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_lis_import_user FOREIGN KEY (imported_by) REFERENCES trac_jhs_sarms.users(id),
    CONSTRAINT fk_lis_import_year FOREIGN KEY (school_year_id) REFERENCES trac_jhs_sarms.school_years(id)
);

INSERT INTO app_settings (setting_key, setting_value) VALUES
    ('lis_school_id', '000000'),
    ('lis_division', 'Division of Tawi-Tawi')
ON CONFLICT (setting_key) DO NOTHING;