-- Phase 5: Public admission inquiry submissions.
-- Run AFTER schema.sql on existing installations. Idempotent — IF NOT EXISTS
-- guards make it safe to apply either before or after schema.sql. No-op on
-- fresh installs that already have the table (none yet — schema.sql does not
-- create this table; this migration introduces it).
--
-- Retention: indefinite. Inquiry rows are not auto-purged. The status column
-- (new/spam/processed/duplicate) lets registrar staff mark rows without
-- deleting, preserving a DPA-friendly audit trail. If institutional policy
-- later requires a purge window, add a retention_days setting to app_settings
-- and a purge function modeled on 004_audit_retention.sql's
-- purge_old_audit_logs().
--
-- Pre-existing privacy.php / RA 10173 / Data Privacy Act framing in this repo
-- covers audit_logs retention (5y default). No equivalent requirement has been
-- documented for inquiries; this migration deliberately does not invent one.
--
-- Scope note: only the fields the public inquiry form actually collects
-- (full_name, grade, contact_number) are persisted. No IP, no user agent,
-- no other PII beyond what the visitor voluntarily provided.

SET search_path = trac_jhs_sarms, public;

CREATE TABLE IF NOT EXISTS inquiries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    grade           VARCHAR(15)  NOT NULL,
    contact_number  VARCHAR(30)  NOT NULL,
    status          VARCHAR(15)  NOT NULL DEFAULT 'new'
                    CHECK (status IN ('new', 'spam', 'processed', 'duplicate')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_inquiries_grade CHECK (grade IN
        ('Grade 7', 'Grade 8', 'Grade 9', 'Grade 10'))
);

-- Lookup indexes: registrar admin views will filter by status + sort by date.
CREATE INDEX IF NOT EXISTS idx_inquiries_status_created
    ON inquiries (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_inquiries_created
    ON inquiries (created_at DESC);

-- Re-use the project's standard updated_at trigger function (created in
-- schema.sql). If this migration is applied to a DB that pre-dates the
-- function, recreate it locally first.
CREATE TRIGGER trg_inquiries_updated_at
    BEFORE UPDATE ON inquiries
    FOR EACH ROW EXECUTE FUNCTION trac_jhs_sarms.trigger_set_updated_at();